name: Birthday

on:
  schedule:
    - cron: "0 0 14 5 *" # This runs every Sunday at midnight UTC

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: write
  
jobs:
  update-bday:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Update years old
        run: perl -0pi -e 's/(\d+)(?= years old)/$1+1/ge' README.md
      - name: Commit report
        run: |
          git config --global user.name ${{ secrets.USER_NAME }}
          git config --global user.email ${{ secrets.USER_EMAIL }}
          git commit -am "Happy birthday! 🥳"
          git push

